services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_server
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/servidor
    working_dir: /servidor
    command: "uvicorn main:app --host :: --reload"
    restart: on-failure
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    dns_opt:
      - "inet6"
    environment:
      - PYTHONUNBUFFERED=1
      - PREFER_IPV4=1 # For√ßar IPv4 para acessos externos
    extra_hosts:
      - "youtube.com:142.250.191.174"
      - "www.youtube.com:142.250.191.174"
      - "googlevideo.com:142.250.191.174"
    networks:
      app_network:
        ipv6_address: 2001:db8:1::10

  frontend:
    depends_on:
      - backend
    build:
      context: ./interface
      dockerfile: Dockerfile
    container_name: interface_app
    ports:
      - "5173:5173"
    volumes:
      - ./interface:/app
      - /app/node_modules
    environment:
      - VITE_YOUTUBE_API_KEY=${VITE_YOUTUBE_API_KEY}
    working_dir: /app
    command: npm run dev -- --host
    restart: always
    networks:
      app_network:
        ipv6_address: 2001:db8:1::20

networks:
  app_network:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
        - subnet: 2001:db8:1::/64
          gateway: 2001:db8:1::1
